###############################################################################
# Licensed Materials - Property of IBM
# (c) Copyright IBM Corporation 2021. All Rights Reserved.
#
# Note to U.S. Government Users Restricted Rights:
# Use, duplication or disclosure restricted by GSA ADP Schedule
# Contract with IBM Corp.
###############################################################################

## Playbook that creates local Zowe profiles for the host provided

---
- hosts: "{{ host | default('sandbox1') }}"
  collections:
    - ibm.ibm_zos_core
  gather_facts: no
  environment: "{{ environment_vars }}"

  vars_prompt:
    - name: password
      prompt: "Password for the z/OS user?"

  tasks:

  # Variables and template prep
  - name: Defining user-specific variables
    set_fact:
      hlq: "{{ ansible_user | upper }}"

  - name: Execute the generated script '~/.zowe/zowecli-create-profiles.sh' to create Zowe CLI profiles for the host {{ ansible_host }}.
    template:
      src: zowecli-create-profiles.j2
      dest: ~/.zowe/zowecli-create-profiles.sh
      mode: u+rwx
    delegate_to: localhost

  - name: Copy or merge the generated launch file '~/.zowe/launch.json' for the host {{ ansible_host }} to your top-level workspace directory .vscode or .theia.
    template:
      src: debug-launch.j2
      dest: ~/.zowe/launch.json
      mode: ugo+rw
    delegate_to: localhost

  - name: Copy-paste these settings into Z Open Editor or Wazi Developer for Workspaces to configure Debug.
    set_fact:
      settings:
        "{'zopendebug.connection.connectionName': '{{ ansible_host }}',
          'zopendebug.connection.connectionPort': '{{ debug_profile_service_port_ssl }}',
          'zopendebug.connection.userName': '{{ ansible_user }}'
         }"

  - name: Show the sample user settings object
    debug:
      var: settings
