###############################################################################
# Licensed Materials - Property of IBM
# (c) Copyright IBM Corporation 2021. All Rights Reserved.
#
# Note to U.S. Government Users Restricted Rights:
# Use, duplication or disclosure restricted by GSA ADP Schedule
# Contract with IBM Corp.
###############################################################################

################################################################################
# Environment variables for all z/OS managed nodes (target) that do not need
# further configuration.
################################################################################
environment_vars:
  _BPXK_AUTOCVT: "ON"
  ZOAU_HOME: "{{ zoau }}"
  # PYTHONPATH: "{{ zoau }}/lib" # Only enable when using Python that was not installed via pip
  ROCKET: "{{ rocket }}"
  GIT_EXEC_PATH: "{{ rocket }}/libexec/git-core"
  JAVA_HOME: "{{ java_home }}"
  LIBPATH: "{{ zoau }}/lib:{{ pyz }}/lib:/lib:/usr/lib:."
  PATH: "{{ zoau }}/bin:{{ pyz }}/bin:{{ rocket }}/bin:/bin:/var/bin"
  _CEE_RUNOPTS: "FILETAG(AUTOCVT,AUTOTAG) POSIX(ON)"
  _TAG_REDIR_ERR: "txt"
  _TAG_REDIR_IN: "txt"
  _TAG_REDIR_OUT: "txt"
  LANG: "C"
  DBB_HOME: "{{ dbb_home }}"
  DBB_CONF: "{{ dbb_conf }}"

################################################################################
# Description of the properties used in this configuration:
################################################################################
# - Property BPXK_AUTOCVT must be configured to "ON"; e.g., _BPXK_AUTOCVT: "ON"
# - Property ZOAU_HOME is the ZOA Utilities install root path; e.g., ZOAU_HOME: "/usr/lpp/IBM/zoautil"
# - Property PYTHONPATH is the ZOA Utilities Python library path; e.g., PYTHONPATH: "/usr/lpp/IBM/zoautil/lib"
# - Property LIBPATH is both the path to the Python libraries on the target
#   and the ZOA Utilities Python library path separated by semi-colons; e.g.,
#   LIBPATH: "/usr/lpp/IBM/zoautil/lib/:/usr/lpp/IBM/cyp/v3r8/pyz/lib:/usr/lib:/lib:."
# - Property PATH is the ZOA utilities BIN path and Python interpreter path, e.g.,
#   PATH: "/usr/lpp/IBM/zoautil/bin:/usr/lpp/IBM/cyp/v3r8/pyz/bin:/bin"
# - Property _CEE_RUNOPTS is the invocation Language EnvironmentÂ® runtime
#   options for programs and used by Python. e.g.,
#   _CEE_RUNOPTS: "FILETAG(AUTOCVT,AUTOTAG) POSIX(ON)"
# - Properties __TAG_REDIR_ERR, _TAG_REDIR_IN, _TAG_REDIR_OUT are txt and used
#   by the shell; e.g.,
#      _TAG_REDIR_ERR: "txt"
#      _TAG_REDIR_IN: "txt"
#      _TAG_REDIR_OUT: "txt"
# - Property LANG is the name of the default locale; value
#   C specifies the POSIX locale; for example: ``LANG: "C"``.
################################################################################